if: commit_message =~ /(Upgrade|Trigger|Update|Fix|Add|Create|Rename)/
language: node_js
node_js:
  - "10"
cache: yarn
before_install:
  - npm install -g yarn
  - git pull https://github.com/BLHXFY-Group/BLHXFY.git master
jobs:
  include:
    - stage: trigger downstream
      if: repo = BLHXFY-Group/BLHXFY
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          sh ./script/trigger-travis.sh biuuu BLHXFY $TRAVIS_ACCESS_TOKEN
        fi
    - stage: deploy
      if: repo = biuuu/BLHXFY
      script:
        - yarn travis_deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  committer_from_gh: true
  on:
    branch: master
    repo: biuuu/BLHXFY
